#!/usr/bin/env python3
"""
Create demo ROMs and test files for emulator
"""
from pathlib import Path
import zipfile
import io
import struct

BASE = Path(__file__).parent
ROMS = BASE / "roms"
ROMS.mkdir(exist_ok=True)

def create_demo_sisx():
    """Create a demo SISX package"""
    buf = io.BytesIO()
    z = zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED)

    # PKG file
    pkg_content = """
; Demo SISX package
; Generated by OldPhoneEmulator

#{"DemoApp"}

(0x10000001), 1, 0, 0, {"DemoApp"}

"system/apps/DemoApp/DemoApp.app" - "!:\\system\\apps\\DemoApp\\DemoApp.app"
"system/apps/DemoApp/DemoApp.rsc" - "!:\\system\\apps\\DemoApp\\DemoApp.rsc"

%{"Vendor"}
:"Vendor"

%{"EN"}
:"DemoApp"
:"DemoApp"
    """
    z.writestr("DemoApp.pkg", pkg_content)
    z.writestr("system/apps/DemoApp/DemoApp.app", b"\x00\x01\x02\x03 DemoApp E32Image fake")
    z.writestr("system/apps/DemoApp/DemoApp.rsc", b"Resource file")
    z.writestr("META-INF/MANIFEST.MF", "Manifest-Version: 1.0\n")
    z.close()

    out = ROMS / "DemoApp.sisx"
    out.write_bytes(buf.getvalue())
    print(f"✅ Created {out} ({out.stat().st_size} bytes)")

def create_demo_jar():
    """Create a demo JAR MIDlet"""
    buf = io.BytesIO()
    z = zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED)

    manifest = """Manifest-Version: 1.0
MIDlet-Name: DemoMIDlet
MIDlet-Version: 1.0
MIDlet-Vendor: OldPhoneEmulator
MIDlet-1: DemoMIDlet, /icon.png, DemoMIDlet
MicroEdition-Configuration: CLDC-1.1
MicroEdition-Profile: MIDP-2.0
"""
    z.writestr("META-INF/MANIFEST.MF", manifest)
    z.writestr("DemoMIDlet.class", b"\xCA\xFE\xBA\xBE fake class file")
    z.writestr("icon.png", b"\x89PNG fake")
    z.close()

    out = ROMS / "DemoMIDlet.jar"
    out.write_bytes(buf.getvalue())
    print(f"✅ Created {out} ({out.stat().st_size} bytes)")

def create_demo_rofs():
    """Create a fake ROFS header for testing"""
    data = bytearray(1024*1024)  # 1MB
    # Fake ROFS signature
    data[0:4] = b"ROFS"
    data[4:8] = struct.pack("<I", 0x100000)  # size
    data[8:12] = struct.pack("<I", 0x40000000)  # load address
    data[12:16] = struct.pack("<I", 0x40001000)  # entry
    # Add some strings
    data[0x100:0x100+20] = b"Symbian OS 9.2 S60 3rd"
    data[0x200:0x200+10] = b"Nokia N95"
    data[0x300:0x300+8] = b"EPOC32"

    out = ROMS / "N95_ROFS2_demo.bin"
    out.write_bytes(bytes(data))
    print(f"✅ Created {out} ({out.stat().st_size/1024:.0f} KB)")

def create_demo_exe():
    """Create minimal PE for testing"""
    data = bytearray(1024)
    data[0:2] = b"MZ"
    data[0x3C:0x40] = struct.pack("<I", 0x80)
    data[0x80:0x84] = b"PE\x00\x00"
    data[0x84:0x86] = struct.pack("<H", 0x14c)  # I386
    data[0x86:0x88] = struct.pack("<H", 1)
    data[0x94:0x96] = struct.pack("<H", 0xE0)
    data[0x98:0x9A] = struct.pack("<H", 0x10b)  # PE32
    data[0xA8:0xAC] = struct.pack("<I", 0x1000)
    data[0xB4:0xB8] = struct.pack("<I", 0x400000)
    # Add Symbian string
    data[0x200:0x207] = b"Symbian"

    out = ROMS / "demo_win32.exe"
    out.write_bytes(bytes(data))
    print(f"✅ Created {out}")

def create_demo_elf():
    """Create minimal ELF for testing"""
    data = bytearray(1024)
    data[0:4] = b"\x7fELF"
    data[4] = 1  # 32-bit
    data[5] = 1  # little endian
    data[16:18] = struct.pack("<H", 2)  # ET_EXEC
    data[18:20] = struct.pack("<H", 0x28)  # ARM
    data[24:28] = struct.pack("<I", 0x8000)  # entry

    out = ROMS / "demo_linux.elf"
    out.write_bytes(bytes(data))
    print(f"✅ Created {out}")

def create_demo_iso():
    """Create minimal ISO with CD001 signature"""
    data = bytearray(0x9000 + 2048)
    # PVD at 0x8000
    data[0x8000] = 1  # Primary Volume Descriptor
    data[0x8001:0x8006] = b"CD001"
    data[0x8006] = 1
    data[0x8008:0x8028] = b"LINUX                   "
    data[0x8028:0x8048] = b"DEMO_ISO                "
    data[0x8050:0x8054] = struct.pack("<I", 10)  # volume size
    data[0x8054:0x8058] = struct.pack(">I", 10)
    # Boot
    data[0x8800] = 0
    data[0x8801:0x8806] = b"CD001"
    data[0x8806] = 1
    data[0x8807:0x8827] = b"EL TORITO SPECIFICATION"

    out = ROMS / "demo_disk.iso"
    out.write_bytes(bytes(data))
    print(f"✅ Created {out} ({out.stat().st_size/1024:.0f} KB)")

if __name__ == "__main__":
    print("📦 Creating demo ROMs for OldPhoneEmulator...\n")
    create_demo_sisx()
    create_demo_jar()
    create_demo_rofs()
    create_demo_exe()
    create_demo_elf()
    create_demo_iso()
    print(f"\n✅ All demo files created in {ROMS}/")
    print("   You can now run: python main.py --web")
